<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ page import="java.util.Date" %>
<%@ page isELIgnored="false" %>
<%@ page buffer="8kb" %>
<%@ page errorPage="error.jsp" %>
<%@ page info="It is an example of page directive attributes" %>
<%@ page isThreadSafe="false" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
	<h1 align="center">JSP Page directive attributes</h1>
	<div style="padding: 20px; background-color:#a5d6c2;">
		<h3>1. import </h3>
		<p>The import attribute is used to import class,interface or all the members of a package.It is similar to import keyword in java class or interface.</p>
		<p>&lt;%@ page import="java.util.Date" %&gt;</p>
		<p>Today is: <%= new Date() %> </p> 
	</div>
	<br/>
	<div style="padding: 20px; background-color:#a5d6c2;">
		<h3>2. contentType, language </h3>
		<p>The contentType attribute defines the MIME(Multipurpose Internet Mail Extension) type of the HTTP response.The default value is "text/html;charset=ISO-8859-1".</p>
		<p>The language attribute specifies the scripting language used in the JSP page. The default value is "java".</p>
		<p>&lt;%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%&gt;</p>
	</div>
	<br/>
	<div style="padding: 20px; background-color:#a5d6c2;">
		<h3>3. buffer </h3>
		<p>The buffer attribute sets the buffer size in kilobytes to handle output generated by the JSP page.The default size of the buffer is 8Kb.</p>
		<p>&lt;%@ page buffer="16kb" %&gt;  </p>
	</div>
	<br/>
	<div style="padding: 20px; background-color:#a5d6c2;">
		<h3>4. isELIgnored </h3>
		<p>We can ignore the Expression Language (EL) in jsp by the isELIgnored attribute. By default its value is false i.e. Expression Language is enabled by default.</p>
		<p>&lt;%@ page isELIgnored="true" %&gt;  </p>
		
		<jsp:include page="include_param.jsp">
			<jsp:param name="fname" value="${name}"/>
		</jsp:include>
	</div>
	<br/>
	<div style="padding: 20px; background-color:#a5d6c2;">
		<h3>5. errorPage </h3>
		<p>The errorPage attribute is used to define the error page, if exception occurs in the current page, it will be redirected to the error page.</p>
		<p>&lt;%@ page errorPage="error.jsp" %&gt;  </p>
		<%= 100/1 %>  
	</div>
	<br/>
	<div style="padding: 20px; background-color:#a5d6c2;">
		<h3>6. isErrorPage </h3>
		<p>The isErrorPage attribute is used to declare that the current page is the error page.</p>
		<p>&lt;%@ page isErrorPage="true" %&gt;  </p>
	</div>
	<br/>
	<div style="padding: 20px; background-color:#a5d6c2;">
		<h3>7. info </h3>
		<p>This attribute simply sets the information of the JSP page.</p>
		<p>&lt;%@ page info="It is an example of page directive attributes" %&gt;  </p>
	</div>
	<br/>
	<div style="padding: 20px; background-color:#a5d6c2;">
		<h3>8. isThreadSafe </h3>
		<p>Servlet and JSP both are multithreaded.If you want to control this behaviour of JSP page, you can use isThreadSafe attribute of page directive.The value of isThreadSafe value is true.If you make it false, the web container will serialize the multiple requests, i.e. it will wait until the JSP finishes responding to a request before passing another request to it.</p>
		<p>&lt;%@ page isThreadSafe="false" %&gt;  </p>
	</div>
</body>
</html>